# Generated by Django 5.0.2 on 2024-06-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_name_customer_password_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirm_password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
