# Generated by Django 3.2.25 on 2024-08-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_id',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
