# Generated by Django 3.2.25 on 2024-08-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20240815_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customers.cart'),
        ),
    ]
