# Generated by Django 3.2.25 on 2024-08-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_order_cartid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartid',
        ),
    ]
